services:

  backend_app:
    build:
      context: .
      dockerfile: backend_app.dockerfile
    ports:
      - 8000:8000

  frontend_app:
    build:
      context: frontend_app
      dockerfile: Dockerfile
    environment:
      - ENDPOINT_URL=http://backend_app:8000
    ports:
      - 8501:8501