apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app-pod
        image: hearbet_detector_frontend:01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENDPOINT_URL
          value: http://backend-app.default.svc.cluster.local:8000
        ports:
        - containerPort: 8501
